SELECT
    A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM
    APPOINTMENT A INNER JOIN
    PATIENT P INNER JOIN
    DOCTOR D
    ON
        A.PT_NO = P.PT_NO AND
        A.MDDR_ID = D.DR_ID
WHERE
    A.APNT_CNCL_YN = 'N' AND
    A.APNT_YMD >= '2022-04-13' AND
    A.APNT_YMD < '2022-04-14'
ORDER BY
    A.APNT_YMD ASC