SELECT B.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM (PATIENT A INNER JOIN APPOINTMENT B ON A.PT_NO = B.PT_NO) LEFT OUTER JOIN DOCTOR C ON C.DR_ID = B.MDDR_ID
WHERE B.APNT_CNCL_YN LIKE 'N%' AND B.APNT_YMD >= "2022-4-13" AND B.APNT_YMD < "2022-4-14"
ORDER BY B.APNT_YMD ASC