SELECT
    FP.PRODUCT_ID, FP.PRODUCT_NAME,
    (SUM(FO.AMOUNT) * FP.PRICE) AS TOTAL_SALES
FROM
    FOOD_PRODUCT FP INNER JOIN
    FOOD_ORDER FO
    ON
        FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE
    FO.PRODUCE_DATE >= '2022-05-01' AND
    FO.PRODUCE_DATE < '2022-06-01'
GROUP BY
    FP.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    FP.PRODUCT_ID ASC