#문자열 비교 => Like %
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A INNER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE Like "Intact%" AND (B.SEX_UPON_OUTCOME Like "Spayed%" OR B.SEX_UPON_OUTCOME Like "Neutered%")