SELECT
    YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH,
    COUNT(DISTINCT UI.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE OS LEFT OUTER JOIN
    USER_INFO UI
    ON
        OS.USER_ID = UI.USER_ID
WHERE
    YEAR(UI.JOINED) = 2021
GROUP BY
    YEAR(OS.SALES_DATE),
    MONTH(OS.SALES_DATE)
ORDER BY
    YEAR ASC,
    MONTH ASC