# USER_INFO : USER_ID, GENDER, AGE, JOINED
# GENDER => 0:남자 1:여자
# ONLINE_SALE : ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE

# USER_INFO와 ONLINE_SALES에서 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년, 월 별로 출력하세요

# 결과는 YEAR, MONTH, PURCHASED_USERS, PURCHASED_RATIO

SELECT
    YEAR(A.SALES_DATE) YEAR, MONTH(A.SALES_DATE) MONTH,
    COUNT(DISTINCT B.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PURCHASED_RATIO
FROM
    ONLINE_SALE A LEFT OUTER JOIN 
    USER_INFO B
    ON
        A.USER_ID = B.USER_ID
WHERE
        YEAR(B.JOINED) = 2021
GROUP BY
    YEAR(A.SALES_DATE),
    MONTH(A.SALES_DATE)
ORDER BY
    YEAR ASC,
    MONTH ASC